name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Run Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run Check
        uses: actions-rs/cargo@v1
        with:
          command: check
